spring:
  redis:
    host: localhost
    port: 6379
    password: 1234qwer
    timeout: 300ms
  rabbitmq:
    addresses: localhost
    port: 5672
    virtual-host: base_vhost
    username: guest
    password: guest
#    # 开启回调
#    publisher-confirm-type: correlated
#    #
#    publisher-returns: true
#    listener:
#      type: simple
#      simple:
#        # 手动确认
#        acknowledge-mode: manual
#        # 限制每次发送一条数据
#        prefetch: 1
#        # 同一个队列启动几个消费者
#        concurrency: 3
#        # 启动消费者最大数量
#        max-concurrency: 3
#        # 重试策略相关配置
#        retry:
#          # 是否支持重试
#          enabled: true
#          max-attempts: 5
#          stateless: false
#          # 时间策略乘数因子
#          multiplier: 1.0
#        default-requeue-rejected: true







